const fs = require('node:fs');
const path = require('node:path');
const { createCipheriv, createHash, randomBytes, scryptSync } = require('node:crypto');
const PDFDocument = require('pdfkit');

const { getSystemConfig } = require('./configService');

const STORAGE_DIRECTORY = path.join(__dirname, '..', '..', 'storage', 'papers');
const MAGIC_HEADER = Buffer.from('EVLT02', 'utf8');

function sanitizeSegment(value) {
  return String(value || 'paper')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function buildRegisterNumberBoxes(doc, startX, startY) {
  doc.fontSize(10).font('Helvetica-Bold').text('Register Number:', startX, startY);
  const boxY = startY + 16;

  for (let index = 0; index < 12; index += 1) {
    doc.rect(startX + index * 18, boxY, 16, 16).stroke('#9ca3af');
  }
}

function decoratePage(doc, watermarkText, config, pageNumber) {
  doc.save();
  doc.fillColor('#d6d9de');
  doc.fillOpacity(0.16);
  doc.fontSize(38);
  doc.rotate(-35, {
    origin: [doc.page.width / 2, doc.page.height / 2]
  });
  doc.text(watermarkText, 40, doc.page.height / 2 - 30, {
    align: 'center',
    width: doc.page.width - 80
  });
  doc.restore();

  doc
    .moveTo(doc.page.margins.left, 42)
    .lineTo(doc.page.width - doc.page.margins.right, 42)
    .strokeColor('#d1d5db')
    .stroke();

  doc
    .moveTo(doc.page.margins.left, doc.page.height - 55)
    .lineTo(doc.page.width - doc.page.margins.right, doc.page.height - 55)
    .strokeColor('#d1d5db')
    .stroke();

  doc.fillColor('#111827');
  doc.fontSize(9).font('Helvetica');
  doc.text(config.pdf_footer_text || '', doc.page.margins.left, doc.page.height - 48, {
    width: doc.page.width - doc.page.margins.left - doc.page.margins.right - 60
  });
  doc.text(`Page ${pageNumber}`, doc.page.width - doc.page.margins.right - 50, doc.page.height - 48, {
    align: 'right',
    width: 50
  });
}

async function renderPdfBuffer({ subject, blueprint, sections, examDate, faculty }) {
  const config = getSystemConfig();

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 54,
      bufferPages: true
    });
    const chunks = [];
    const watermarkText = `Generated ${new Intl.DateTimeFormat('en-IN', {
      dateStyle: 'medium'
    }).format(new Date())} | Faculty ${faculty.id} ${faculty.name}`;

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => {
      resolve(Buffer.concat(chunks));
    });

    if (config.pdfLogoPath && fs.existsSync(config.pdfLogoPath)) {
      try {
        doc.image(config.pdfLogoPath, doc.page.margins.left, 55, {
          fit: [60, 60],
          align: 'left'
        });
      } catch (error) {
        // Ignore invalid image payloads and continue with text-only header.
      }
    }

    doc.fontSize(18).font('Helvetica-Bold').text(config.pdf_university_name || 'ExamVault University', 0, 55, {
      align: 'center'
    });
    doc.moveDown(0.1);
    doc.fontSize(12).font('Helvetica').text(config.pdf_header_text || 'Confidential Question Paper', {
      align: 'center'
    });
    doc.moveDown(0.8);

    buildRegisterNumberBoxes(doc, doc.page.margins.left, 115);
    doc.moveDown(2.8);

    doc.fontSize(16).font('Helvetica-Bold').text(blueprint.paperTitle || 'University Examination', {
      align: 'center'
    });
    doc.moveDown(0.8);

    doc.fontSize(11).font('Helvetica');
    doc.text(`Subject: ${subject.name} (${subject.code})`);
    doc.text(`Exam Date: ${new Intl.DateTimeFormat('en-IN', { dateStyle: 'long' }).format(new Date(examDate))}`);
    doc.text(`Duration: ${blueprint.examDurationMinutes} minutes`);
    doc.text(`Maximum Marks: ${blueprint.totalMarks}`);
    doc.text(`Generated By: ${faculty.name} (Faculty ID ${faculty.id})`);
    doc.moveDown(0.8);
    doc.font('Helvetica-Oblique').text(blueprint.instructions || 'Answer all questions.');
    doc.moveDown(1);

    let questionNumber = 1;

    sections.forEach((section) => {
      doc.fontSize(13).font('Helvetica-Bold').text(section.title, {
        underline: true
      });
      doc.moveDown(0.2);
      doc.fontSize(9).font('Helvetica').fillColor('#6b7280').text(
        `Modules: ${section.allowedModules.join(', ')} | ${section.questionCount} question(s) x ${section.marksPerQuestion} marks | Types: ${section.allowedQuestionTypes.join(', ')}`
      );
      doc.fillColor('#111827');
      doc.moveDown(0.4);

      section.questions.forEach((question) => {
        const body = `Q${questionNumber}. ${question.text}`;
        doc.fontSize(11).font('Helvetica-Bold').text(body, {
          continued: true
        });
        doc.font('Helvetica').text(` (${question.marks} marks)`);
        doc.moveDown(0.15);
        doc
          .fontSize(9)
          .fillColor('#5c6670')
          .text(
            `Module ${question.module} | Difficulty ${question.difficulty_code} | Bloom's ${question.blooms_level} | Type ${question.question_type}`
          );
        doc.fillColor('#111827');
        doc.moveDown(0.7);
        questionNumber += 1;
      });

      doc.moveDown(0.5);
    });

    const range = doc.bufferedPageRange();
    for (let index = range.start; index < range.start + range.count; index += 1) {
      doc.switchToPage(index);
      decoratePage(doc, watermarkText, config, index + 1);
    }

    doc.end();
  });
}

function generateSingleUseAccessKey() {
  return randomBytes(12).toString('base64url').slice(0, 16);
}

function encryptPdfBuffer(pdfBuffer) {
  const accessKey = generateSingleUseAccessKey();
  const salt = randomBytes(16);
  const iv = randomBytes(12);
  const derivedKey = scryptSync(accessKey, salt, 32);
  const cipher = createCipheriv('aes-256-gcm', derivedKey, iv);
  const encrypted = Buffer.concat([cipher.update(pdfBuffer), cipher.final()]);
  const authTag = cipher.getAuthTag();

  return {
    encryptedBuffer: Buffer.concat([MAGIC_HEADER, salt, iv, authTag, encrypted]),
    accessKey,
    keyFingerprint: createHash('sha256').update(accessKey).digest('hex')
  };
}

function saveEncryptedPaper({ encryptedBuffer, subjectCode, examDate }) {
  fs.mkdirSync(STORAGE_DIRECTORY, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.TZ-]/g, '').slice(0, 14);
  const fileName = `${sanitizeSegment(subjectCode)}-${sanitizeSegment(examDate)}-${stamp}.vault`;
  const filePath = path.join(STORAGE_DIRECTORY, fileName);
  fs.writeFileSync(filePath, encryptedBuffer);
  return { fileName, filePath };
}

module.exports = {
  MAGIC_HEADER,
  encryptPdfBuffer,
  renderPdfBuffer,
  saveEncryptedPaper
};
